import { PMConfig, DataSource } from '../types';

export const pmConfig: PMConfig = {
  productPrice: {
    value: 2919,
    unit: '元',
    status: 'pending',
    source: '个人收集材料 / 用户分享价格单',
    updatedAt: '2026-07',
    note: '三个月基础套零售参考总额（大白+小红+小白），具体以官方最新结算单为准。',
  },
  autoBuyPrice: {
    value: 2919,
    unit: '元',
    status: 'pending',
    source: '个人收集材料 / 会员自动购政策',
    updatedAt: '2026-07',
    note: '指自动购计划（Auto-Ship）的单次参考支付总金额（通常按3个月配送计算）。',
  },
  autoBuyCycleDays: {
    value: 90,
    unit: '天',
    status: 'verified',
    source: 'PM官方产品计划指南',
    updatedAt: '2026-07',
    note: '自动购标准周期，一般为每90天配送并扣款一次。',
  },
  dailyCost: {
    value: 32.43,
    unit: '元/天',
    status: 'pending',
    source: '根据2919元/90天折算',
    updatedAt: '2026-07',
    note: '由三个月自动购金额 2919 元除以 90 天得出（约 32.43 元/天），作为单日基础营养成本参考。',
  },
  validPointsPerPerson: {
    value: 103,
    unit: '分',
    status: 'pending',
    source: '个人收集材料 / 存在103分和106分两种口径',
    updatedAt: '2026-07',
    note: '代表一套基础套在系统中的参考有效积分。现有材料存在不同口径，此为演示参数，不代表官方确认标准。',
  },
  bonusCoefficient: {
    value: 0.51,
    unit: '系数',
    status: 'pending',
    source: '个人收集材料 / 演示参考系数',
    updatedAt: '2026-07',
    note: '计算奖金时，积分需乘以该系数进行本币结算折算。此系数为演示参数。',
  },
  exchangeRate: {
    value: 8.2,
    unit: '汇率',
    status: 'pending',
    source: '个人收集材料 / 汇率转换演示值',
    updatedAt: '2026-07',
    note: '系统内部将欧元或点数折算人民币的演示汇率，非即时外汇市场真实汇率，结算以官方实际换算为准。',
  },
  bonusPercentages: {
    value: [0.05, 0.03, 0.03, 0.03, 0.05, 0.05], // 第一代到第六代
    unit: '%',
    status: 'pending',
    source: '个人收集材料 / 演示奖金计划',
    updatedAt: '2026-07',
    note: '演示性的一代至六代奖金比例（分别为：5%, 3%, 3%, 3%, 5%, 5%），实际提成比例和资格要求请参照最新版官方《薪酬计划说明书》。',
  },
  minActivePoints: {
    value: 100,
    unit: '分',
    status: 'pending',
    source: '个人收集材料 / 活跃资格基准',
    updatedAt: '2026-07',
    note: '个人或自动购维持活跃状态以享有代数奖金的最低参考积分条件。',
  },
  planVersion: {
    value: '2026版演示说明规划',
    unit: '版本号',
    status: 'pending',
    source: '自制独立说明整理',
    updatedAt: '2026-07',
    note: '本站独立制作的测算对照版本，非官方发布版本。',
  },
  effectiveDate: {
    value: '2026-07-01',
    unit: '日期',
    status: 'verified',
    source: '本网站发布日期',
    updatedAt: '2026-07',
    note: '此信息包的整理和编写生效时间。',
  },
  disclaimer: {
    value: '本站为独立信息整理与情景测算工具，不是PM官方网站，也不提供医疗诊断或收入保证。产品信息以当地包装和官方说明为准；奖金制度以PM最新正式文件和实际结算为准。所有计算结果均为基于设定的情景模拟演示，不代表您的实际收益，亦不构成任何投资或加盟建议。',
    unit: '文本',
    status: 'verified',
    source: '法律合规声明',
    updatedAt: '2026-07',
    note: '贯穿全站核心页面底部的免责提示信息。',
  },
  wechatContact: {
    value: {
      nickname: 'PM透明了解服务微信',
      account: 'PM_Info_Center',
      qrPlaceholder: '微信二维码占位图',
    },
    unit: '微信联系方式',
    status: 'verified',
    source: '平台管理员配置',
    updatedAt: '2026-07',
    note: '用于引导访客进行合规、中立、不推销式微信咨询的联系人配置。',
  },
};

export const dataSources: DataSource[] = [
  {
    id: 'src-1',
    title: 'PM-International 薪酬计划指南',
    publisher: 'PM-International 官方',
    url: 'https://www.pm-international.com/',
    region: '全球/多区域',
    publishDate: '2025-12',
    checkDate: '2026-07',
    type: '奖金制度文件',
    status: 'pending',
    supports: '一代至六代奖金分配比例（5%、3%、3%、3%、5%、5%）及积分奖金系数',
  },
  {
    id: 'src-2',
    title: 'FitLine 基础三合一产品外包装标签及配料表',
    publisher: 'PM-International 生产质量监督部门',
    url: 'https://www.pm-international.com/',
    region: '中国大陆/亚太版本',
    publishDate: '2025-09',
    checkDate: '2026-07',
    type: '产品包装和标签',
    status: 'verified',
    supports: 'Activize、Basics、Restorate 主要配料、成分及食用建议',
  },
  {
    id: 'src-3',
    title: 'FitLine 自动购计划（Auto-Ship）申请说明书',
    publisher: 'PM-International 销售服务中心',
    url: 'https://www.pm-international.com/',
    region: '中国及亚太区',
    publishDate: '2025-10',
    checkDate: '2026-07',
    type: '产品订阅规则',
    status: 'pending',
    supports: '自动购2919元/90天周期，及103积分起算基础规则',
  },
  {
    id: 'src-4',
    title: '中国直销管理条例与相关公开政策',
    publisher: '中华人民共和国商务部直销行业管理信息系统',
    url: 'http://zxgl.mofcom.gov.cn/',
    region: '中国大陆',
    publishDate: '2018-12',
    checkDate: '2026-07',
    type: '政府和监管资料',
    status: 'verified',
    supports: '合规性提示，多层次与代数奖金在特定国家与地区合规性限制说明',
  }
];
